CREATE TABLE RCOORDI(
    RESNO NUMBER  CONSTRAINT RNO_RCOORDI_PK PRIMARY KEY,
    RESNAME VARCHAR2(20 CHAR) CONSTRAINT RNAME_RCOORDI_NN NOT NULL ENABLE, 
    RESLAT NUMBER CONSTRAINT RLAT_RCOORDI_NN NOT NULL ENABLE, 
    RESLON NUMBER CONSTRAINT RLON_RCOORDI_NN NOT NULL ENABLE, 
    MYLAT NUMBER CONSTRAINT MYLAT_RCOORDI_NN NOT NULL ENABLE, 
    MYLON NUMBER CONSTRAINT MYLON_RCOORDI_NN NOT NULL ENABLE, 
    RESDIST NUMBER CONSTRAINT RDIST_RCOORDI_NN NOT NULL ENABLE, 
    CATEGORY VARCHAR2(20 CHAR)
);