CREATE TABLE  PICKUPPLACE(
    CUSNAME VARCHAR2(10 CHAR) CONSTRAINT CUSNAME_PICKUPPLACE_PK PRIMARY KEY,
    CUSID VARCHAR2(15 CHAR) CONSTRAINT ID_pickupPlace_NN NOT NULL ENABLE, 
    PICKUPLAT NUMBER CONSTRAINT LAT_pickupPlace_NN NOT NULL ENABLE, 
    PICKUPLON NUMBER CONSTRAINT LON_pickupPlace_NN NOT NULL ENABLE, 
    CUS_LAT NUMBER CONSTRAINT cLAT_pickupPlace_NN NOT NULL ENABLE, 
    CUS_LON NUMBER CONSTRAINT cLON_pickupPlace_NN NOT NULL ENABLE, 
    DISTANCE NUMBER CONSTRAINT DIST_pickupPlace_NN NOT NULL ENABLE
);